name: Differ-workflow-test
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  buildAneTest:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v1
        with:
          # Specify the PHP version
          php-version: '7.4'
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true